appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c3122f94e246e0700ce978e
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: QtwKp5Pbv8WxxTS8EMyk3Xj8j4tBygK1oPrdZu6Gr9LGYNlmRrvemUG/48/gTv+dB4CSP9KPu6bU7USvRmsw01XIaXJmBtlKEqH4h8GQ4gVt8YQNbl4Tcp39hDnjneFMh+H22FukqL9lA49WOlKEZfliUZYAqWxXNtEPIWb6RFde3tmv2mwjDcenco6LKOpHGBssSctZ2h5/fPQDxRF1Tx7NDNaf/2iIiR1AE3zNqzPBjZYnJCUSuO9UwB+ZL0h2wTw/PIB+PQDKtmjHjrSxG3OuHqnm2y5b/Zlu9ioUHb5yJxPmPOQSSTiOmsoXFhhBLNVtWWUqsUCmnyZ3h9vID68fb+xOQver/JFD2YVGk6HAAkk5sM1f9ZCq6zwxGK7p5AuEoNzPoUJHNh2BPkk8fluHxCAWmdXpK1dojiPY1MfRRz1WK0xZS5LzrEOu3fU+o4tzvsCxLLm6gkkvvNNctyRljEATgp42xnplZxFSFt4ygq8mePKnvpwy5e4kWgnqAfNcRevNFF1CsXKqyXhqdyqxRuMIPOhEtQGUx+gscEfVo30D222zHofnvbQ0/DDfeU7RnokZ28fXlpYSNHQkPb6guDp70faRVTWMLK0L9FXWktdIIDEBgew8crsqbcej2UWkr2Y5EalS7BDXTMpF1PHOOIc30gCco6iZW1mf1Zc=}
